/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.Mongo;
import com.mongodb.MongoClient;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MTJP Project
 */
public class JFrameTransaksi extends javax.swing.JFrame {
    
    Mongo mongo = null;
    DB db;
    DBCollection collection;
    DBCursor cursor = null;
    MongoClient mongoClient = null;
    /**
     * Creates new form JFrameMenu
     */
    public JFrameTransaksi() {
        initComponents();
        mongoClient = new MongoClient("localhost", 27017);
        db = mongoClient.getDB("warungITB");
        collection = db.getCollection("transaksi");
        cursor = collection.find();
        
        load_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textidPemesan = new javax.swing.JTextField();
        textnamaPegawai = new javax.swing.JTextField();
        textnamaCustomer = new javax.swing.JTextField();
        textmakanan = new javax.swing.JTextField();
        textqty = new javax.swing.JTextField();
        textminuman = new javax.swing.JTextField();
        textqtyy = new javax.swing.JTextField();
        texttotal = new javax.swing.JTextField();
        btnedit = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltransaksi = new javax.swing.JTable();
        btnhapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("WARUNG MAKAN ITB");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nama Makanan");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Nama Minuman");

        jLabel20.setText("Pepes Ikan Tongkol Merah");

        jLabel21.setText("Pepes Ikan Tongkol Semayi");

        jLabel22.setText("Pepes Tahu");

        jLabel23.setText("Ikan Bakar Bawal");

        jLabel24.setText("Sayur Asem");

        jLabel25.setText("Nasi Putih");

        jLabel26.setText("Teh Botol Sosro");

        jLabel27.setText("Fruity Apel");

        jLabel28.setText("Fruity Anggur");

        jLabel29.setText("Air Mineral");

        jLabel30.setText("Beras Kencur");

        jLabel31.setText("Kunir Asem");

        jLabel3.setText("ID Pemesanan");

        jLabel4.setText("Nama Customer");

        jLabel6.setText("Nama Pegawai");

        jLabel7.setText("Makanan");

        jLabel8.setText("QTY");

        jLabel9.setText("Minuman");

        jLabel10.setText("QTY");

        jLabel11.setText("Total Harga");

        btnedit.setText("Update");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btnadd.setText("Tambah");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        tbltransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Pemesan", "Nama Pegawai", "Nama Customer", "Makanan", "QTY", "Minuman", "Qty", "Total Harga"
            }
        ));
        tbltransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbltransaksi);

        btnhapus.setText("Delete");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel26))
                                .addGap(163, 163, 163)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(btnadd))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textidPemesan)
                                    .addComponent(textnamaPegawai)
                                    .addComponent(textnamaCustomer)
                                    .addComponent(textmakanan)
                                    .addComponent(textqty)
                                    .addComponent(textminuman)
                                    .addComponent(textqtyy)
                                    .addComponent(texttotal)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnedit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                        .addComponent(btnreset)
                                        .addGap(21, 21, 21)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnhapus)
                                .addGap(51, 51, 51))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(textidPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(textnamaPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textnamaCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(textmakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(textqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(textminuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textqtyy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(texttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnedit)
                            .addComponent(btnreset)
                            .addComponent(btnadd)
                            .addComponent(btnhapus))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void load_table(){
        DefaultTableModel model = (DefaultTableModel) tbltransaksi.getModel();
        while(cursor.hasNext()){
            DBObject obj = cursor.next();
        
            String textidPemesan = (String)obj.get("idPemesan");
            String textnamaPegawai = (String)obj.get("namaPegawai");
            String textnamaCustomer = (String)obj.get("namaCustomer");
            String textmakanan = (String)obj.get("namaMakanan");
            String textqty = (String)obj.get("qty");
            String textminuman = (String)obj.get("namaMinuman");
            String textqtyy = (String)obj.get("qtyy");
            String texttotal = (String)obj.get("totalHarga");
            
            model.addRow(new Object[] {
                textidPemesan, textnamaPegawai, textnamaCustomer, textmakanan, textqty,
                textminuman, textqtyy, texttotal
            });
        }
        tbltransaksi.setModel(model);
    }

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        
        BasicDBObject add = new BasicDBObject();
        add.put("idPemesan", textidPemesan.getText());
        add.put("namaPegawai", textnamaPegawai.getText());
        add.put("namaCustomer", textnamaCustomer.getText());
        add.put("namaMakanan", textmakanan.getText());
        add.put("qty", textqty.getText());
        add.put("namaMinuman", textminuman.getText());
        add.put("qtyy", textqtyy.getText());
        add.put("totalHarga", texttotal.getText());
        
        collection.insert(add);

        tbl.addRow(new Object[] {
            textidPemesan.getText(), textnamaPegawai.getText(), textnamaCustomer.getText(), textmakanan.getText(), textqty.getText(),
                textminuman.getText(), textqtyy.getText(), texttotal.getText()
    });
        tbltransaksi.setModel(tbl);
        textidPemesan.setText("");
        textnamaPegawai.setText("");
        textnamaCustomer.setText("");
        textmakanan.setText("");
        textqty.setText("");
        textminuman.setText("");
        textqtyy.setText("");
        texttotal.setText("");
    }//GEN-LAST:event_btnaddActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        tbltransaksi.setModel(tbl);
    }//GEN-LAST:event_formComponentShown

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        BasicDBObject indexupdate = new BasicDBObject();
        indexupdate.put("idPemesan", textidPemesan.getText());
        BasicDBObject update = new BasicDBObject();
        update.put("idPemesan", textidPemesan.getText());
        update.put("namaPegawai", textnamaPegawai.getText());
        update.put("namaCustomer", textnamaCustomer.getText());
        update.put("namaMakanan", textmakanan.getText());
        update.put("qty", textqty.getText());
        update.put("namaMinuman", textminuman.getText());
        update.put("qtyy", textqtyy.getText());
        update.put("totalHarga", texttotal.getText());
        
        tbl.setValueAt(textidPemesan.getText(), Baris, 0);
        tbl.setValueAt(textnamaPegawai.getText(), Baris, 1);
        tbl.setValueAt(textnamaCustomer.getText(), Baris, 2);
        tbl.setValueAt(textmakanan.getText(), Baris, 3);
        tbl.setValueAt(textqty.getText(), Baris, 4);
        tbl.setValueAt(textminuman.getText(), Baris, 5);
        tbl.setValueAt(textqtyy.getText(), Baris, 6);
        tbl.setValueAt(texttotal.getText(), Baris, 7);
        reset();
        tbltransaksi.setModel(tbl);
        collection.update(indexupdate, update);
    }//GEN-LAST:event_btneditActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        BasicDBObject indexhapus = new BasicDBObject();
        indexhapus.put("idPemesan", textidPemesan.getText());
        
        collection.remove(indexhapus);
        tbl.removeRow(Baris);
        reset();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void tbltransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltransaksiMouseClicked
        // TODO add your handling code here:
        int baris = tbltransaksi.rowAtPoint(evt.getPoint());
        String id = tbltransaksi.getValueAt(baris, 0).toString();
        textidPemesan.setText(id);
        String namaPegawai = tbltransaksi.getValueAt(baris, 1).toString();
        textnamaPegawai.setText(namaPegawai);
        String namaCustomer = tbltransaksi.getValueAt(baris, 2).toString();
        textnamaCustomer.setText(namaCustomer);
        String makan = tbltransaksi.getValueAt(baris, 3).toString();
        textmakanan.setText(makan);
        String qty = tbltransaksi.getValueAt(baris, 4).toString();
        textqty.setText(qty);
        String minum = tbltransaksi.getValueAt(baris, 5).toString();
        textminuman.setText(minum);
        String qtyy = tbltransaksi.getValueAt(baris, 6).toString();
        textqtyy.setText(qtyy);
        String tot = tbltransaksi.getValueAt(baris, 7).toString();
        texttotal.setText(tot);
    }//GEN-LAST:event_tbltransaksiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTransaksi().setVisible(true);
            }
        });
    }
    
    int Baris = 0;
    static Object kolom[] = {"ID Pemesan", "Nama Pegawai", "Nama Customer", "Nama Makanan", "QTY", "Nama Minuman", "QTYY", "Total Harga"};
    DefaultTableModel tbl = new DefaultTableModel(kolom, Baris);

    void reset(){
        textidPemesan.setText("");
        textnamaPegawai.setText("");
        textnamaCustomer.setText("");
        textmakanan.setText("");
        textqty.setText("");
        textminuman.setText("");
        textqtyy.setText("");
        texttotal.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbltransaksi;
    private javax.swing.JTextField textidPemesan;
    private javax.swing.JTextField textmakanan;
    private javax.swing.JTextField textminuman;
    private javax.swing.JTextField textnamaCustomer;
    private javax.swing.JTextField textnamaPegawai;
    private javax.swing.JTextField textqty;
    private javax.swing.JTextField textqtyy;
    private javax.swing.JTextField texttotal;
    // End of variables declaration//GEN-END:variables
}
