/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author MTJP Project
 */
import com.mongodb.BasicDBObject;
import com.mongodb.Mongo;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import javax.swing.table.DefaultTableModel;

public class JFramePegawai extends javax.swing.JFrame {

    /**
     * Creates new form JFramePegawai
     */
    
    Mongo mongo = null;
    DB db;
    DBCollection collection;
    DBCursor cursor = null;
    MongoClient mongoClient = null;
    
    public JFramePegawai() {
        initComponents();
        mongoClient = new MongoClient("localhost", 27017);
        db = mongoClient.getDB("warungITB");
        collection = db.getCollection("pegawai");
        cursor = collection.find();
        
        load_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void load_table(){
        DefaultTableModel model = (DefaultTableModel) tblpegawai.getModel();
        while(cursor.hasNext()){
            DBObject obj = cursor.next();
            String textidP = (String)obj.get("idPegawai");
            String textnamaP = (String)obj.get("namaPegawai");
            String textuserP = (String)obj.get("userPegawai");
            String textpassP = (String)obj.get("passPegawai");
            String textalamatP = (String)obj.get("alamatPegawai");
            String textnotelpP = (String)obj.get("notelpPegawai");
            
            model.addRow(new Object[]{
                textidP, textnamaP, textuserP, textpassP, textalamatP, textnotelpP

            });
        }
        tblpegawai.setModel(model);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textidP = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpegawai = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textnamaP = new javax.swing.JTextField();
        textuserP = new javax.swing.JTextField();
        textpassP = new javax.swing.JTextField();
        textalamatP = new javax.swing.JTextField();
        textnotelpP = new javax.swing.JTextField();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Pegawai");

        btnadd.setText("Simpan");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        tblpegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Pegawai", "Nama Pegawai", "Username Pegawai", "Password Pegawai", "Alamat Pegawai", "No Telp Pegawai"
            }
        ));
        tblpegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpegawai);

        jLabel4.setText("ID Pegawai");

        jLabel5.setText("Nama Pegawai");

        jLabel6.setText("Username Pegawai");

        jLabel7.setText("Password Pegawai");

        jLabel8.setText("Alamat Pegawai");

        jLabel9.setText("No Telp Pegawai");

        textuserP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textuserPActionPerformed(evt);
            }
        });

        btnedit.setText("Update");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnreset.setBackground(new java.awt.Color(255, 0, 0));
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnedit)
                                .addGap(30, 30, 30)
                                .addComponent(btndelete)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textalamatP, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textnotelpP, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(46, 46, 46)
                                .addComponent(btnadd)
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textpassP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                                    .addComponent(textuserP, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textnamaP, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textidP, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnreset)
                                .addGap(35, 35, 35))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textidP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreset)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textnamaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textuserP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textpassP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textalamatP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textnotelpP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadd)
                    .addComponent(jLabel9))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndelete)
                    .addComponent(btnedit))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textuserPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textuserPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textuserPActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        textidP.setText("");
        textnamaP.setText("");
        textuserP.setText("");
        textpassP.setText("");
        textnotelpP.setText("");
        textalamatP.setText("");
        textnotelpP.setText("");
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        BasicDBObject add = new BasicDBObject();
        add.put("idPegawai", textidP.getText());
        add.put("namaPegawai", textnamaP.getText());
        add.put("userPegawai", textuserP.getText());
        add.put("passPegawai", textpassP.getText());
        add.put("alamatPegawai", textalamatP.getText());
        add.put("notelpPegawai", textnotelpP.getText());
        
        collection.insert(add);
        
        tbl.addRow(new Object[] {
        textidP.getText(), textnamaP.getText(), textuserP.getText(), textpassP.getText(), textalamatP.getText(), textnotelpP.getText()
    });
        tblpegawai.setModel(tbl);
        textidP.setText("");
        textnamaP.setText("");
        textuserP.setText("");
        textpassP.setText("");
        textalamatP.setText("");
        textnotelpP.setText("");
        
    }//GEN-LAST:event_btnaddActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        
        BasicDBObject indexupdate = new BasicDBObject();
        indexupdate.put("idPegawai", textidP.getText());
        BasicDBObject update = new BasicDBObject();
        update.put("namaPegawai", textnamaP.getText());
        update.put("userPegawai", textuserP.getText());
        update.put("passPegawai", textpassP.getText());
        update.put("alamatPegawai", textalamatP.getText());
        update.put("notelpPegawai", textnotelpP.getText());
        
        tbl.setValueAt(textidP.getText(), baris, 0);
        tbl.setValueAt(textnamaP.getText(), baris, 1);
        tbl.setValueAt(textuserP.getText(), baris, 2);
        tbl.setValueAt(textpassP.getText(), baris, 3);
        tbl.setValueAt(textalamatP.getText(), baris, 4);
        tbl.setValueAt(textnotelpP.getText(), baris, 5);
        reset();
        tblpegawai.setModel(tbl);
        collection.update(indexupdate, update);
    }//GEN-LAST:event_btneditActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        tblpegawai.setModel(tbl);
    }//GEN-LAST:event_formComponentShown

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        BasicDBObject indexhapus = new BasicDBObject();
        indexhapus.put("idPegawai", textidP.getText());
        
        tbl.setValueAt(textidP.getText(), baris, 0);
        tbl.setValueAt(textnamaP.getText(), baris, 1);
        tbl.setValueAt(textuserP.getText(), baris, 2);
        tbl.setValueAt(textpassP.getText(), baris, 3);
        tbl.setValueAt(textalamatP.getText(), baris, 4);
        tbl.setValueAt(textnotelpP.getText(), baris, 5);
        
        collection.remove(indexhapus);
        tbl.removeRow(baris);
        reset();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void tblpegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpegawaiMouseClicked
        // TODO add your handling code here:
        
        int baris = tblpegawai.rowAtPoint(evt.getPoint());
        String id = tblpegawai.getValueAt(baris, 0).toString();
        textidP.setText(id);
        String nama = tblpegawai.getValueAt(baris, 1).toString();
        textnamaP.setText(nama);
        String user = tblpegawai.getValueAt(baris, 2).toString();
        textuserP.setText(user);
        String pass = tblpegawai.getValueAt(baris, 3).toString();
        textpassP.setText(pass);
        String alamat = tblpegawai.getValueAt(baris, 4).toString();
        textalamatP.setText(alamat);
        String notelp = tblpegawai.getValueAt(baris, 5).toString();
        textnotelpP.setText(notelp);
    }//GEN-LAST:event_tblpegawaiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePegawai().setVisible(true);
            }
        });
    }
    
    int baris = 0;
    static Object kolom[] = {"ID Pegawai", "Nama Pegawai", "Username Pegawai", "Password Pegawai", "Alamat Pegawai", "No Telp Pegawai"};
    DefaultTableModel tbl = new DefaultTableModel(kolom, baris);

    void reset(){
        textidP.setText("");
        textnamaP.setText("");
        textuserP.setText("");
        textpassP.setText("");
        textalamatP.setText("");
        textnotelpP.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblpegawai;
    private javax.swing.JTextField textalamatP;
    private javax.swing.JTextField textidP;
    private javax.swing.JTextField textnamaP;
    private javax.swing.JTextField textnotelpP;
    private javax.swing.JTextField textpassP;
    private javax.swing.JTextField textuserP;
    // End of variables declaration//GEN-END:variables
}
